#!/usr/bin/env python
# -*- coding: utf-8 -*-
from general import NULL

def dbstr(s): 
	return str(s)

def dbstr2(s): 
	return s.encode("utf-8")

def dbint(i):
	if i in ("", "."):
		return 0
	return int(i)

def dbfloat(i):
	if i in ("", "."):
		return 0.0
	return float(i)

DATABASE_PATH = {
	"item": "./data/item.csv",
	"item2": "./data/item2.csv",
	"item3": "./data/item3.csv",
	"item4": "./data/item4.csv",
	"item5": "./data/item5.csv",
	"item6": "./data/item6.csv",
	"job": "./data/job.csv",
	"map": "./data/map.csv",
	"monster": "./data/monster.csv",
	"npc": "./data/npc.csv",
	"pet": "./data/pet.csv",
	"partner": "./data/partner_info.csv",
	"shop": "./data/shop.csv",
	"skill": "./data/skill.csv",
}

DATABASE_ROW_MAP_RAW = {
	"item": {
		u"#ItemID": (dbint, "item_id"),
		u"PictID": (dbint, "pict_id"),
		u"IconID": NULL,
		u"アイテム名": (dbstr2, "name"),
		u"種別ID": (dbstr2, "type"),
		u"値段": (dbint, "price"),
		u"重量": (dbint, "weight"), #payl
		u"容量": (dbint, "capa"),
		u"装備時容量": NULL,
		u"憑依重量（未使用）": NULL,
		u"修理": NULL,
		u"強化ID（未使用）": NULL,
		u"処理フラグ0": NULL,
		u"Event": NULL,
		u"レシピ可": NULL,
		u"染色": NULL,
		u"ストック": (dbint, "stock"),
		u"両手": NULL,
		u"使用時消滅": (dbint, "disposable"),
		u"色": (dbint, "color"),
		u"耐久度": (dbint, "durability_max"),
		u"ジョイントジョブＩＤ": NULL,
		u"初期イリスカードスロット数": NULL,
		u"アイテムチェンジ可否フラグ": NULL,
		u"イベントＩＤ": (dbint, "event_id"),
		u"エフェクトＩＤ": NULL,
		u"発動Skill": (dbint, "skill_id"),
		u"使用可能Skill": (dbint, "skill_id_add"),
		u"パッシブスキル": NULL,
		u"憑依時可能Skill": NULL,
		u"憑依パッシブSkill": NULL,
		u"ターゲットタイプ": NULL,
		u"発動タイプ": NULL,
		u"射程": NULL,
		u"効果時間": NULL,
		u"効果範囲": NULL,
		u"効果値": NULL,
		u"キャスト": NULL,
		u"ディレイ": NULL,
		u"HP上昇": (dbint, "hp"),
		u"MP上昇": (dbint, "mp"),
		u"SP上昇": (dbint, "sp"),
		u"最大重量上昇": (dbint, "payl_add"),
		u"最大容量上昇": (dbint, "capa_add"),
		u"移動力上昇": (dbint, "speed"),
		u"STR": (dbint, "str"),
		u"MAG": (dbint, "mag"),
		u"VIT": (dbint, "vit"),
		u"DEX": (dbint, "dex"),
		u"AGI": (dbint, "agi"),
		u"INT": (dbint, "int"),
		u"LUK": (dbint, "luk"),
		u"CHA": (dbint, "cha"),
		u"物理攻撃力(叩)": (dbint, "atk1"),
		u"物理攻撃力(斬)": (dbint, "atk2"),
		u"物理攻撃力(突)": (dbint, "atk3"),
		u"魔法攻撃力": (dbint, "matk"),
		u"物理防御力": (dbint, "DEF"),
		u"魔法防御力": (dbint, "mdef"),
		u"近命中力": (dbint, "s_hit"),
		u"遠命中力": (dbint, "l_hit"),
		u"魔法命中力": (dbint, "magic_hit"),
		u"近回避力": (dbint, "s_avoid"),
		u"遠回避力": (dbint, "l_avoid"),
		u"魔回避力": (dbint, "magic_avoid"),
		u"クリ力": (dbint, "critical_hit"),
		u"クリ回避": (dbint, "critical_avoid"),
		u"回復力": (dbint, "heal_hp"),
		u"魔法回復力": (dbint, "heal_mp"),
		u"無": (dbint, "energy"),
		u"火": (dbint, "fire"),
		u"水": (dbint, "water"),
		u"風": (dbint, "wind"),
		u"土": (dbint, "earth"),
		u"光": (dbint, "light"),
		u"闇": (dbint, "dark"),
		u"毒": (dbint, "poison"),
		u"石化": (dbint, "stone"),
		u"麻痺": (dbint, "paralyze"),
		u"睡眠": (dbint, "sleep"),
		u"沈黙": (dbint, "silence"),
		u"鈍足": (dbint, "slow"),
		u"混乱": (dbint, "confuse"),
		u"凍結": (dbint, "freeze"),
		u"気絶": (dbint, "stan"),
		u"エミル種族": NULL,
		u"タイタニア種族": NULL,
		u"ドミニオン種族": NULL,
		u"DEM種族": NULL,
		u"男": NULL,
		u"女": NULL,
		u"LV": NULL,
		u"転生": NULL,
		u"装備可STR": NULL,
		u"装備可MAG": NULL,
		u"装備可VIT": NULL,
		u"装備可DEX": NULL,
		u"装備可AGI": NULL,
		u"装備可INT": NULL,
		u"装備可LUK": NULL,
		u"装備可CHA": NULL,
		u"ノービス": NULL,
		u"ソードマン": NULL,
		u"ブレマス": NULL,
		u"バウンテ": NULL,
		u"フェンサ": NULL,
		u"ナイト": NULL,
		u"ダークスト": NULL,
		u"スカウト": NULL,
		u"アサシン": NULL,
		u"コマンド": NULL,
		u"アーチャ": NULL,
		u"ストライ": NULL,
		u"ガンナー": NULL,
		u"ウィザ": NULL,
		u"ソーサラ": NULL,
		u"セージ": NULL,
		u"シャーマン": NULL,
		u"エレメン": NULL,
		u"エンチャン": NULL,
		u"ウァテス": NULL,
		u"ドルイド": NULL,
		u"バード": NULL,
		u"ウォーロ": NULL,
		u"カバリ": NULL,
		u"ネクロマ": NULL,
		u"タタラベ": NULL,
		u"ブラスミ": NULL,
		u"マシンナ": NULL,
		u"ファーマ": NULL,
		u"アルケミ": NULL,
		u"マリオネ": NULL,
		u"レンジャ": NULL,
		u"エクスプ": NULL,
		u"トレジャ": NULL,
		u"マーチャ": NULL,
		u"トレーダ": NULL,
		u"ギャンブラー": NULL,
		u"グラディエイター": NULL,
		u"ガーディアン": NULL,
		u"イレイザー": NULL,
		u"ホークアイ": NULL,
		u"フォースマスター": NULL,
		u"アストラリスト": NULL,
		u"カーディナル": NULL,
		u"ソウルテイカー": NULL,
		u"マエストロ": NULL,
		u"ハーヴェスト": NULL,
		u"ストライダー": NULL,
		u"ロイヤルディーラー": NULL,
		u"ジョーカー": NULL,
		u"東軍": NULL,
		u"西軍": NULL,
		u"南軍": NULL,
		u"北軍": NULL,
		u"所属５": NULL,
		u"所属６": NULL,
		u"所属７": NULL,
		u"所属８": NULL,
		u"ブリーダー": NULL,
		u"ガーデナー": NULL,
		u"フラグ３": NULL,
		u"フラグ４": NULL,
		u"フラグ５": NULL,
		u"フラグ６": NULL,
		u"フラグ７": NULL,
		u"変身ＩＤ": NULL,
		u"封印モンＩＤ": (dbint, "pet_id"),
		u"片手モーションID": (dbint, "s_motion"),
		u"両手モーションID": (dbint, "d_motion"),
		u"右手憑依者モーション": NULL,
		u"左手憑依者モーション": NULL,
		u"胸アクセ憑依者モーション": NULL,
		u"鎧憑依者モーション": NULL,
		u"アイテム欄コメント": NULL,
		u"国内ITEM": NULL,
		u"国内ITEM2": NULL,
		u"検索フラグ": NULL,
		u"ワールド用リサイクルポイント": NULL,
	},
	"item3": {
		u"#ItemID": (dbint, "item_id"),
		u"PictID": (dbint, "pict_id"),
		u"IconID": NULL,
		u"アイテム名": (dbstr2, "name"),
		u"種別ID": (dbstr2, "type"),
		u"値段": (dbint, "price"),
		u"重量": (dbint, "weight"), #payl
		u"容量": (dbint, "capa"),
		u"装備時容量": NULL,
		u"憑依重量（未使用）": NULL,
		u"修理": NULL,
		u"強化ID（未使用）": NULL,
		u"処理フラグ0": NULL,
		u"Event": NULL,
		u"レシピ可": NULL,
		u"染色": NULL,
		u"ストック": (dbint, "stock"),
		u"両手": NULL,
		u"使用時消滅": (dbint, "disposable"),
		u"色": (dbint, "color"),
		u"耐久度": (dbint, "durability_max"),
		u"ジョイントジョブＩＤ": NULL,
		u"初期イリスカードスロット数": NULL,
		u"アイテムチェンジ可否フラグ": NULL,
		u"イベントＩＤ": (dbint, "event_id"),
		u"エフェクトＩＤ": NULL,
		u"発動Skill": (dbint, "skill_id"),
		u"使用可能Skill": (dbint, "skill_id_add"),
		u"パッシブスキル": NULL,
		u"憑依時可能Skill": NULL,
		u"憑依パッシブSkill": NULL,
		u"ターゲットタイプ": NULL,
		u"発動タイプ": NULL,
		u"射程": NULL,
		u"効果時間": NULL,
		u"効果範囲": NULL,
		u"効果値": NULL,
		u"キャスト": NULL,
		u"ディレイ": NULL,
		u"HP上昇": (dbint, "hp"),
		u"MP上昇": (dbint, "mp"),
		u"SP上昇": (dbint, "sp"),
		u"最大重量上昇": (dbint, "payl_add"),
		u"最大容量上昇": (dbint, "capa_add"),
		u"移動力上昇": (dbint, "speed"),
		u"STR": (dbint, "str"),
		u"MAG": (dbint, "mag"),
		u"VIT": (dbint, "vit"),
		u"DEX": (dbint, "dex"),
		u"AGI": (dbint, "agi"),
		u"INT": (dbint, "int"),
		u"LUK": (dbint, "luk"),
		u"CHA": (dbint, "cha"),
		u"物理攻撃力(叩)": (dbint, "atk1"),
		u"物理攻撃力(斬)": (dbint, "atk2"),
		u"物理攻撃力(突)": (dbint, "atk3"),
		u"魔法攻撃力": (dbint, "matk"),
		u"物理防御力": (dbint, "DEF"),
		u"魔法防御力": (dbint, "mdef"),
		u"近命中力": (dbint, "s_hit"),
		u"遠命中力": (dbint, "l_hit"),
		u"魔法命中力": (dbint, "magic_hit"),
		u"近回避力": (dbint, "s_avoid"),
		u"遠回避力": (dbint, "l_avoid"),
		u"魔回避力": (dbint, "magic_avoid"),
		u"クリ力": (dbint, "critical_hit"),
		u"クリ回避": (dbint, "critical_avoid"),
		u"回復力": (dbint, "heal_hp"),
		u"魔法回復力": (dbint, "heal_mp"),
		u"無": (dbint, "energy"),
		u"火": (dbint, "fire"),
		u"水": (dbint, "water"),
		u"風": (dbint, "wind"),
		u"土": (dbint, "earth"),
		u"光": (dbint, "light"),
		u"闇": (dbint, "dark"),
		u"毒": (dbint, "poison"),
		u"石化": (dbint, "stone"),
		u"麻痺": (dbint, "paralyze"),
		u"睡眠": (dbint, "sleep"),
		u"沈黙": (dbint, "silence"),
		u"鈍足": (dbint, "slow"),
		u"混乱": (dbint, "confuse"),
		u"凍結": (dbint, "freeze"),
		u"気絶": (dbint, "stan"),
		u"エミル種族": NULL,
		u"タイタニア種族": NULL,
		u"ドミニオン種族": NULL,
		u"DEM種族": NULL,
		u"男": NULL,
		u"女": NULL,
		u"LV": NULL,
		u"転生": NULL,
		u"装備可STR": NULL,
		u"装備可MAG": NULL,
		u"装備可VIT": NULL,
		u"装備可DEX": NULL,
		u"装備可AGI": NULL,
		u"装備可INT": NULL,
		u"装備可LUK": NULL,
		u"装備可CHA": NULL,
		u"ノービス": NULL,
		u"ソードマン": NULL,
		u"ブレマス": NULL,
		u"バウンテ": NULL,
		u"フェンサ": NULL,
		u"ナイト": NULL,
		u"ダークスト": NULL,
		u"スカウト": NULL,
		u"アサシン": NULL,
		u"コマンド": NULL,
		u"アーチャ": NULL,
		u"ストライ": NULL,
		u"ガンナー": NULL,
		u"ウィザ": NULL,
		u"ソーサラ": NULL,
		u"セージ": NULL,
		u"シャーマン": NULL,
		u"エレメン": NULL,
		u"エンチャン": NULL,
		u"ウァテス": NULL,
		u"ドルイド": NULL,
		u"バード": NULL,
		u"ウォーロ": NULL,
		u"カバリ": NULL,
		u"ネクロマ": NULL,
		u"タタラベ": NULL,
		u"ブラスミ": NULL,
		u"マシンナ": NULL,
		u"ファーマ": NULL,
		u"アルケミ": NULL,
		u"マリオネ": NULL,
		u"レンジャ": NULL,
		u"エクスプ": NULL,
		u"トレジャ": NULL,
		u"マーチャ": NULL,
		u"トレーダ": NULL,
		u"ギャンブラー": NULL,
		u"グラディエイター": NULL,
		u"ガーディアン": NULL,
		u"イレイザー": NULL,
		u"ホークアイ": NULL,
		u"フォースマスター": NULL,
		u"アストラリスト": NULL,
		u"カーディナル": NULL,
		u"ソウルテイカー": NULL,
		u"マエストロ": NULL,
		u"ハーヴェスト": NULL,
		u"ストライダー": NULL,
		u"ロイヤルディーラー": NULL,
		u"ジョーカー": NULL,
		u"東軍": NULL,
		u"西軍": NULL,
		u"南軍": NULL,
		u"北軍": NULL,
		u"所属５": NULL,
		u"所属６": NULL,
		u"所属７": NULL,
		u"所属８": NULL,
		u"ブリーダー": NULL,
		u"ガーデナー": NULL,
		u"フラグ３": NULL,
		u"フラグ４": NULL,
		u"フラグ５": NULL,
		u"フラグ６": NULL,
		u"フラグ７": NULL,
		u"変身ＩＤ": NULL,
		u"封印モンＩＤ": (dbint, "pet_id"),
		u"片手モーションID": (dbint, "s_motion"),
		u"両手モーションID": (dbint, "d_motion"),
		u"右手憑依者モーション": NULL,
		u"左手憑依者モーション": NULL,
		u"胸アクセ憑依者モーション": NULL,
		u"鎧憑依者モーション": NULL,
		u"アイテム欄コメント": NULL,
		u"国内ITEM": NULL,
		u"国内ITEM2": NULL,
		u"検索フラグ": NULL,
		u"ワールド用リサイクルポイント": NULL,
	},
	"job": {
		u"#job_id": (dbint, "job_id"),
		u"job_name": (dbstr, "name"),
		u"hp_rate": (dbfloat, "hp_rate"),
		u"mp_rate": (dbfloat, "mp_rate"),
		u"sp_rate": (dbfloat, "sp_rate"),
		u"payl_rate": (dbfloat, "payl_rate"),
		u"capa_rate": (dbfloat, "capa_rate"),
	},
	"map": {
		u"#マップＩＤ": (dbint, "map_id"),
		u"マップ名": (dbstr, "name"),
		u"中心座標ｘ": (dbfloat, "centerx"),
		u"中心座標ｙ": (dbfloat, "centery"),
	},
	"monster": {
		u"##": (dbint, "monster_id"),
		u"体格": NULL,
		u"特殊情報": NULL,
		u"設定": NULL,
		u"基本パラメータ": NULL,
		u"ステータス": NULL,
		u"物理攻撃": NULL,
		u"魔法攻撃": NULL,
		u"防御力": NULL,
		u"命中": NULL,
		u"回避": NULL,
		u"クリティカル": NULL,
		u"攻撃速度": NULL,
		u"属性値": NULL,
		u"状態異常耐性": NULL,
		u"思考ID(通常）": NULL,
		u"思考(出現)": NULL,
		u"思考ID(瀕死)": NULL,
		u"思考(終焉）": NULL,
		u"スキルリスト": NULL,
		u"↓減少HP%分加算": NULL,
		u"↓減少HP%分減算": NULL,
		u"↓ボス召喚時のスキル": NULL,
		u"↓最初最後使用するスキル": NULL,
		u"経験値": NULL,
		u"ドロップ": NULL,
		u"ドロップアイテム": NULL,
		u"旅人のメモ": NULL,
		u"パーティ": NULL,
	},
	"npc": {
		u"#NPCID": (dbint, "npc_id"),
		u"NAME": (dbstr, "name"),
		u"MAPID": NULL,
		u"座標Ｘ": NULL,
		u"座標Ｙ": NULL,
		u"方向": NULL,
		u"scale": NULL,
		u"EVENTID": NULL,
		u"NOTOUCH": NULL,
		u"ＰＩＣＴＩＤ": NULL,
		u"初期モーション": NULL,
		u"透明度(0~255)この値を 0 以外にすると重くなるので注意してください": NULL,
		u"デフォルト表示": NULL,
		u"円形影の描画": NULL,
		u"FLAG": NULL,
		u"NPC表示設定": NULL,
	},
	"pet": {
		u"#PETID": (dbint, "pet_id"),
		u"ペット名": (dbstr, "name"),
		u"PICTID": (dbint, "pict_id"),
		u"移動速度": (dbint, "speed"),
		u"種別ID": NULL,
		u"体の幅": NULL,
		u"体の長さ": NULL,
		u"スケール": NULL,
		u"特殊情報": NULL,
		u"基本パラメータ": NULL,
		u"戦闘パラメータ": NULL,
		u"属性値": NULL,
		u"状態異常耐性": NULL,
		u"思考ID(通常時）": NULL,
		u"思考ID(出現時)": NULL,
		u"思考ID(瀕死時)": NULL,
		u"思考ID(終焉時）": NULL,
		u"スキルリスト": NULL,
		u"EXP": NULL,
		u"JOBEXP": NULL,
		u"ドロップアイテム": NULL,
		u"ドロップアイテム": NULL,
		u"騎乗者非表示設定": NULL,
		u"備考": NULL,
	},
	"partner": {
		u"#パートナーID": (dbint, "pet_id"),
		u"パートナー名": (dbstr2, "name"),
		u"PICTID": (dbint, "pict_id"),
		u"移動速度": (dbint, "speed"),
	},
	"shop": {
		u"#ショップID": (dbint, "shop_id"),
		u"商品ID1": (dbint, 1),
		u"商品ID2": (dbint, 2),
		u"商品ID3": (dbint, 3),
		u"商品ID4": (dbint, 4),
		u"商品ID5": (dbint, 5),
		u"商品ID6": (dbint, 6),
		u"商品ID7": (dbint, 7),
		u"商品ID8": (dbint, 8),
		u"商品ID9": (dbint, 9),
		u"商品ID10": (dbint, 10),
		u"商品ID11": (dbint, 11),
		u"商品ID12": (dbint, 12),
		u"商品ID13": (dbint, 13),
	},
	"skill": {
		u'"ID"': (dbint, "skill_id"),
		u'"Name"': (dbstr, "name"),
		u'"説明"': NULL,
		u'"Active"': NULL,
		u'"MaxLv"': (dbint, "maxlv"),
		u'"Lv"': NULL,
		u'"MP"': NULL,
		u'"SP"': NULL,
		u'"HP"': NULL,
		u'"射程"': NULL,
		u'"ターゲット"': NULL,
		u'"ターゲット2"': NULL,
		u'"範囲"': NULL,
		u'"適応"': NULL,
		u'"Zero"': NULL,
		u'"Flag"': NULL,
		u'"?"': NULL,
		u'"nTarget2"': NULL,
		u'"射程"': NULL,
		u'"0"': NULL,
		u'"MarkTarget"': NULL,
		u'"MarkTarget"': NULL,
		u'"MarkCaster"': NULL,
		u'"icon"': NULL,
		u'"MarkTarget"': NULL,
		u'"0"': NULL,
		u'"mark?"': NULL,
		u'"MarkRound"': NULL,
		u'"MarknewObj"': NULL,
		u'"AnimStart"': NULL,
		u'"AnimLoop"': NULL,
		u'"AnimAttack"': NULL,
	},
}

DATABASE_ROW_MAP_EXT = {
	"item": {
		#3: (dbstr, "name"),
	},
	"item3": {
		#3: (dbstr, "name"),
	},
	"job": {},
	"map": {},
	"monster": {
		1: (dbstr, "name"),
	},
	"npc": {},
	"pet": {
		19: (dbint, "maxhp"),
	},
	"partner": {},
	"shop": {},
	"skill": {},
}